- lakefile.lean
> chore(lakefile.lean): update syntax

- .github/workflows/build.yml
Per https://leanprover.zulipchat.com/#narrow/stream/180721-mathlib-maintainers/topic/build.20servers/near/263171378 (in #maintainers).
> ci: clean up thoroughly at end of workflow

- Mathport/Syntax/Translate/Tactic/Lean3.lean
From https://github.com/leanprover-community/mathport/pull/49#discussion_r758163258
> fix: regression in trHave with optional type/ident

- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib.lean
- config.json
- lakefile.lean
This is the mathport side of leanprover-community/mathlib4#141 .
> chore: snake case tactics

- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Notation.lean
This adds support for the extended binders as implemented in https://github.com/leanprover-community/mathlib4/blob/master/Mathlib/Init/ExtendedBinder.lean . It does not have full coverage of everything lean 3 binder collections can do, so anything outside the covered language is expanded with a warning as before.
> feat: support mathlib4 extended binders

- Mathport/Syntax/Translate/Basic.lean
This makes at least feasible to figure out why pretty-printing fails.  The actual error is typically buried somewhere in the middle of the trace:
```
.... 61 lines of traces
[PrettyPrinter.parenthesize.backtrack] unexpected node kind 'ident', expected 'Mathlib.ExtendedBinder.extBinder'
.... 20 more lines
```
> feat: show parenthesizer traces for errors

- .github/workflows/build.yml
- Mathport.lean
- Mathport/Syntax/Translate/Basic.lean
- config.json
- lakefile.lean
- lean-toolchain
Also cautiously trying to reenable parallelism, which saves a couple of hours of CI time.
> chore: bump to nightly-2021-12-22

- Mathport/Syntax/Transform/Declaration.lean
- Mathport/Syntax/Transform/Tactic.lean
Changes some more unstructured tactics into the structured Lean 4 forms.
> Add more transform rules.

- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Finish.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Linarith.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Monotonicity.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/SolveByElim.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Squeeze.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Suggest.lean
Mathport counterpart of leanprover-community/mathlib4#154 .
> chore: use Parser.Tactic.{config, discharger}

- lakefile.lean
- lean-toolchain
> chore: bump to nightly-2022-01-23

- Mathport/Syntax/Translate/Basic.lean
> fix parens for infix notation

- Mathport/Syntax/Translate/Basic.lean
```diff
-structure simp_config where
+structure SimpConfig where
maxSteps : Nat := Simp.defaultMaxSteps
```
> fix: rename declaration ids

- Mathport/Syntax/Translate/Basic.lean
> fix: truncate precedence to 1024

- Mathport/Binary/Apply.lean
- Mathport/Binary/EnvModification.lean
- Mathport/Binary/ParseTLean.lean
Completely forgot about this. Closes dselsam/binport#26
> feat: binport position information

- Mathport.lean
- Mathport/Binary/TranslateExpr.lean
Fixes #117 (though some coercion definitions are probably still missing).
> fix: expand lean 3 coercions

- Mathport/Syntax/Translate/Basic.lean
> fix: name lookup in open

- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
> fix: use localized in synport

- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/DocCommands.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/NormCast.lean
This is the mathport side of leanprover-community/mathlib4#256 , just a few miscellaneous fixes.
> chore: minor cleanup

- Mathport/Binary/EnvModification.lean
- Mathport/Binary/ParseTLean.lean
- Mathport/Bridge/Config.lean
- Mathport/Bridge/Path.lean
- Mathport/Syntax/AST3.lean
- Mathport/Syntax/Parse.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Command.lean
- Mathport/Syntax/Translate/Expr.lean
- Mathport/Syntax/Translate/Notation.lean
- Mathport/Syntax/Translate/Parser.lean
- Mathport/Util/Json.lean
- Mathport/Util/Misc.lean
- lean-toolchain
- lean_packages/manifest.json
>  chore: bump to 2022-08-31 

- Mathport/Syntax/Translate/Command.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Ext.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
- lean_packages/manifest.json
also fixes the issue from #178
> chore: remove `ext id` and `ancestor` attrs

- Mathport/Syntax/Transform/Declaration.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Core.lean
> feat: translate `mk_simp_attribute`

- Mathport/Binary/Number.lean
> Remove references to `HasZero`/`HasOne`

- Makefile
- Mathport/Syntax/Translate/Parser.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Congr.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Ext.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Interactive.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Linarith.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/NormNum.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/RCases.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Ring.lean
- Oneshot/lean3-in/leanpkg.path
- lean_packages/manifest.json
Companion PR to leanprover-community/mathlib4#536.
> feat: update mathlib mod-tac-stx 2022-11-01

- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
Per https://github.com/leanprover-community/mathlib4/pull/823.
> feat: increment occurrences in nth_rewrite

- Mathport/Syntax/Translate/Tactic/Basic.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Squeeze.lean
- Oneshot/lean4-in/lake-manifest.json
- config.json
- lake-manifest.json
- lean-toolchain
Companion PR to leanprover-community/mathlib4#992.
> feat: update mathlib mod-tac-stx 2022-12-01

- Mathport/Binary/TranslateName.lean
- Mathport/Util/SmartNaming.lean
For each theorem, use the alignments for names appearing in the type of the theorem to make a smart guess for the Lean 4 translated name.
> feat: smart naming for theorems

- Makefile
- Oneshot/README.md
Hopefully addresses some issues encountered while @digama0 helped me debug running oneshot on a mac.
> Corrections to readme and makefile

- Mathport/Syntax/Translate/Command.lean
- lake-manifest.json
* depends on: leanprover-community/mathlib4#4712
> feat: precedence in notation3

- .docker/Dockerfile
The dockerfile annoyingly did not come with `leanproject` and company. This fixes it.
> fix: Make Docker install `mathlibtools`

- README.md
I just ran mathport on a second project on my computer and noticed this minor glitch in the docs.
> olean -> oleans
