- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib.lean
- Mathport/Util/Misc.lean
- lakefile.lean
The only significant "regression" is that options to the `#lint` command are no longer translated.  I've already couldn't figure out how to match on the syntax to write an elaborator in mathlib, and I don't think it's easier to construct the syntax here.  Luckily the `#lint` command is used zero times in mathlib so this shouldn't be a huge issue.
Companion PR to https://github.com/leanprover-community/mathlib4/pull/102
> chore: bump mathlib4 and lean

- lakefile.lean
I don't understand what happened here:
* @gebner's PR was passed by continuous integration: https://github.com/leanprover-community/mathport/actions/runs/1491599884
* but when we merge it into master continuous integration failed: https://github.com/leanprover-community/mathport/actions/runs/1492566005
It seems that the commit sha for mathlib4 that Gabriel added just doesn't exist:
```
% git show 75b0024c6e720126877e415c744bbe1f01e841e5
fatal: bad object 75b0024c6e720126877e415c744bbe1f01e841e5
```
Perhaps someone force pushed ...?
> fix: mathlib4 commit sha

- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib.lean
Lean 4 now uses `split` as a souped-up version of `split_ifs`. It seems likely that we can replace all calls to `split` in Lean3/mathlib3 with `constructor` (which is in principle more powerful: it tries all constructors).
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Renaming.20.60split.60
If we're concerned about this breaking something it alternatively shouldn't be too hard to backport replacing `split` with `constructors` in mathlib3.
> feat: translate Lean3 split tactic to Lean 4 constructor

- .github/workflows/build.yml
Too many CI builds are failing because the disk is full. Let's delete everything before *and* after the build.
> clean up before and after build

- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib.lean
Produce clearer output when the parenthesizer fails.  Instead of the Lean 3 version (which I always mistook for Lean 4 code), it now outputs a best-effort reprinted version of the syntax tree:
```lean
-- failed to parenthesize: parenthesize: uncaught backtrack exception
-- failed to format: format: uncaught backtrack exception
protected
theorem
add_left_cancel
: ∀ { n m k : ℕ } , n + m = n + k → m = k
| 0 , m , k => by simp ( config := { contextual := Bool.true._@._internal._hyg.0 } ) [ Nat.zero_add ]
| succ n , m , k => fun h => have : n + m = n + k := by simp [ succ_add ] at h assumption add_left_cancel this
```
> fix: fall back to reprinter

- Makefile
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Util/Misc.lean
- lakefile.lean
- lean-toolchain
Hopefully this will resolve the problems with `lake` in the downstream `lean3port` and `mathlib3port`?
> bump: nightly-2021-12-15

- Mathport.lean
- Mathport/Syntax/Transform.lean
- Mathport/Syntax/Transform/Basic.lean
- Mathport/Syntax/Transform/Declaration.lean
- Mathport/Syntax/Transform/Tactic.lean
- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
- config.json
Adds a `mathport_rules` command that allows rewriting the syntax after translation.  For example the following makes `instance` declarations use `where blocks:
```lean
mathport_rules
| `(instance $[$id:declId]? $sig:declSig := { $[$fieldName:ident := $fieldVal:term $[,]?]* }) =>
`(instance $[$id:declId]? $sig:declSig where $[$fieldName:ident := $fieldVal:term]*)
```
(The code includes the full rule, which also matches docstrings, etc.)
The above rule will only pretty-print nicely starting with tomorrow's nightly, so let's wait with merging this PR.
> feat: mathport_rules

- Mathport/Syntax/Translate/Basic.lean
- lakefile.lean
The mathport counterpart of leanprover-community/mathlib4#142 : since `notation3` uses `extBinders` instead of `explicitBinders`, the syntax generation has to accommodate the new syntax kind (and associated grammar changes). Depends on leanprover-community/mathlib4#144 .
> feat: add support for extBinders in notation3

- Mathport/Syntax/Translate/Basic.lean
The Lean 4 doc comment parser also trims the doc comments on the left side.  There is a discussion to be had about whether `/--` should be followed by a newline or not, but I'd like to stay consistent with core.
> fix: trim doc comment

- Mathport/Syntax/Transform/Tactic.lean
- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
The simplification eliminates the `TacticContext` flag entirely. Now `trTactic` always produces a `tactic`, and `trBlock` always produces a `tacticSeq`. When these are mismatched, it is possible for an extra `by · $seq` to be introduced, so the transform stage eliminates this (also `:= by · $seq` which is technically a separate grammar production).
Also adds a bunch more transforms:
* `· · $seq` probably won't come up much but I think it is a possible result of the unoptimized translation. I decided against doing `· $seq; · $seq2` -> `· $seq; $seq2` because it is not uncommon to see this construction after a `by_cases` where we don't want to break the symmetry of subgoals.
* `from by` -> `by` in `show` and `suffices` (which I think is the only place this can arise, but I did not check)
* …
> feat: simplify trTactic, add more transforms

- Mathport/Syntax/Transform/Tactic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Apply.lean
- lakefile.lean
Most of these changes are not so interesting, but we can now compile all of lean3 and a decent chunk of mathlib (running locally now) with zero backtrack exceptions.
@gebner The changes in `Syntax/Transform/Tactic.lean` might interest you. The first change removes a redundant match arm; this was doubly surprising since it both did not warn/error on the duplicate branch, and it also did not elaborate the body at all, so there was no warning about the fact that the variable `seq` referenced in that branch does not exist. The second change is a workaround for leanprover/lean4#917 : `suffices T by exact x` was getting replaced by `suffices T x`, and there doesn't seem to be an easy way to avoid this with the bottom up syntax transform mechanism.
> fix: assorted backtrack exception bugfixes

- .github/workflows/build.yml
- Makefile
- config.json
@gebner Re: https://github.com/leanprover-community/mathport/commit/4e5c5820d13555fa884d18003496841a0ee95db8#commitcomment-65848790 what if we just don't copy to `PreData` at all? This commit removes the folder completely.
> chore: don't bother with PreData folder

- Makefile
- Mathport.lean
- Mathport/Bridge/Path.lean
- Mathport/Syntax/AST3.lean
- Mathport/Syntax/Parse.lean
- Mathport/Syntax/Transform/Basic.lean
- Mathport/Syntax/Transform/Tactic.lean
- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Parser.lean
- Mathport/Syntax/Translate/Tactic/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Core.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/DocCommands.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Finish.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Hint.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Interactive.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Squeeze.lean
- MathportApp.lean
- README.md
- config.json
- download-release.sh
This works by annotating the translated `Syntax` objects with synthetic positions from the Lean 3 source file (using 10000*line+column as the string position).  The `trExpr` function therefore now takes an argument of type `Spanned Expr` instead of `Expr` and implicitly uses `withRef` so that syntax quotations add the desired range.  If the resulting syntax still doesn't have a range (e.g. because it is constructed manually), then `trExpr` sets the info on the resulting syntax.  Before the syntax is printed (but after transformations), the comments are inserted into the syntax at reasonable positions.
Fixes #101
> feat: translate comments

- Mathport/Syntax/AST3.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Notation.lean
This is the mathport counterpart of leanprover-community/mathlib4#196, adding support for generating foldl notations. It works to translate the notation itself, but the uses of the notation still do not resolve correctly due to a bug in lean 3 notation name generation that is addressed in leanprover-community/lean#687.
> feat: add support for fold notations

- .docker/Dockerfile
This outdated URL was breaking CI in mathlib earlier today.
> fix: update elan URL

- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Command.lean
- Mathport/Syntax/Translate/Expr.lean
- Mathport/Syntax/Translate/Tactic/Builtin.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc1.lean
The file is used by everything, so any change requires a lot of recompilation.  Just as bad, editing `trExpr'` requires extreme patience since it's at the very end of this long file.
> refactor: split Mathport.Syntax.Translate.Basic

- Makefile
- Mathport.lean
- Mathport/Binary/Apply.lean
- Mathport/Bridge/Config.lean
- Mathport/Bridge/Rename.lean
- Mathport/Syntax.lean
- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Command.lean
- Mathport/Syntax/Translate/Notation.lean
- Mathport/Syntax/Translate/Tactic/Basic.lean
- Mathport/Syntax/Translate/Tactic/Lean3.lean
- config.json
- lean_packages/manifest.json
Definitions that align are now printed like so:
```lean
#print Function.injective_id /-
theorem injective_id : Injective (@id α) := fun a₁ a₂ h => h
-/
```
The comment is the output mathport would have produced, if the definition `Function.injective_id` had not already existed in the environment. This is intended to make it easier to survey an already ported file and quickly identify any new definitions that have been introduced.
> feat: indicate replacements in synport output

- Mathport/Binary/ParseTLean.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Interactive.lean
- Mathport/Util/Misc.lean
This allows for tactics like `recover` and `classical` that have been transformed from regular tactics into block tactics to be able to capture the list of subsequent tactics into the block. (We can't use `Mathport.Syntax.Transform` for this because it's not an adjacent tactic transformation. It's also a mandatory transformation - the result is not well formed if the transformation is not applied - unlike most syntax transforms which are optional.)
> feat: add support for block transforms

- Mathport/Bridge/Config.lean
- Mathport/Syntax/Translate/Basic.lean
- Mathport/Syntax/Translate/Command.lean
- config.json
This implements the option discussed in yesterday's mathport meeting. When the `redundantAlign` config option is set to true (the default), mathport will add a "redundant" `#align` line after every declaration, as a base for modification for when you actually do want an `#align`.
cc: @semorrison @pechersky @gebner
> feat: add `redundantAlign` option

- Mathport/Syntax/AST3.lean
- Mathport/Syntax/Parse.lean
- Mathport/Syntax/Translate/Command.lean
This is blocked on leanprover-community/lean#784 making its way through the pipeline.
The output, while syntactically correct, is pretty rough:
```lean
theorem WellFounded.asymmetric {α : Sort _} {r : α → α → Prop} (h : WellFounded r) : ∀ ⦃a b⦄, r a b → ¬r b a
| a => fun b hab hba => WellFounded.asymmetric hba hab termination_by' ⟨_, h⟩decreasing_by assumption
```
This will need to be fixed in core though. `where` clause formatting is also broken in a similar way:
```lean
/-- The characteristic of the product of rings is the least common multiple of the
characteristics of the two rings. -/
instance [CharP S q] :
CharP (R × S)
(Nat.lcm p
q) where cast_eq_zero_iff := by
simp [Prod.ext_iff, CharP.cast_eq_zero_iff R p, CharP.cast_eq_zero_iff S q, Nat.lcm_dvd_iff]
```
> feat: support `using_well_founded`

- Mathport/Binary/TranslateName.lean
- Mathport/Util/String.lean
Lots of types that started with capital letters were getting "Cat" appended even when it made no sense, e.g., Module.End, LinearMap. Here, we only add the Cat suffix when there is already a conflicting name.
Most of the names that get the Cat suffix are actually categories now. False positives:
https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/names.20distinguished.20only.20by.20case
> fix: adjust cat naming heuristic

- Mathport/Syntax/Parse.lean
When a non-fully-qualified name occurred directly as one of:
* the entire body of a definition/theorem
* an argument to notation (e.g., `a` in `a + 1`)
mathport did not keep track of the pexpr containing the fully-qualified name, and as a result, would not in general translate it to the aligned Lean 4 version. Fix this by passing along the pexpr data.
> fix: keep track of pexpr data

- Mathport/Bridge/Rename.lean
When mathport has to translate a field name (`f` in `x.f`), the correct result must be already in the FieldNameMap, so the old heuristic did not make a lot of sense. Now we at least use a name that exists. This is more of an issue since the introduction of "smart naming" which sometimes generates `names_likeThis`.
> fix: simplify field name heuristic

- .docker/gitpod/Dockerfile
- .gitpod.yml
Notably this ensures a version of ubuntu on which `lake exe cache` works.
In addition to what mathlib4 needs, this installs the relevant C++ compiler tools and the `jq` command line.
> feat: Add gitpod configuration copied from mathlib4

- Mathport/Syntax/Translate/Notation.lean
- Mathport/Syntax/Translate/Tactic/Mathlib/Misc2.lean
- lake-manifest.json
> feat: add support for `matrix.notation`

- Makefile
By putting a `--` after the sha, we ensure that git treats it as a ref and not a filename.
> Harden git checkout calls

- .github/workflows/build.yml
- .github/workflows/predata.yml
- Makefile
- config.json
* The `predata` stage now automatically includes the `.tlean` and `.ast.json` files for `archive` and `counterexamples` in the `mathlib3-predata.tar.gz` export.
* There are two new synport exports, `archive-synport.tar.gz` and `counterexamples-synport.tar.gz`, containing the mathported syntax files. The binport data is not being exported.
* The `update.sh` script on `mathlib3port` needs to be updated if we want it to unpack these files into the repo.
> feat: add CI for archive/ and counterexamples/

- Makefile
Only tested on macos, with both versions.
> chore: make sed work with both gnu sed and macos sed

- Makefile
- Oneshot/README.md
- README.md
* Clarify that this repo might not work on Windows
* reformulate some of the Oneshot README
* add `leanproject get-cache` in the `mathbin-source` command
* Add `git fetch` in the `lean3-source` command.
- This last item conflicts with #232 (note that for mathlib we also do an unrestricted `git fetch`)
> doc: expand readme and makefile

- Mathport/Syntax/Translate.lean
- Mathport/Syntax/Translate/Basic.lean
Mathport still doesn't actually use the `align_import` information, but it does now _generate_ it.
> use #align_import instead of the header comment
